blog/config/routes.rb
Rails.application.routes.draw do
	get 'welcome/index'

	resources :articles do
		resources :comments
	end
	
	
	root 'articles#index'

end

blog/app/models/article.rb
class Article
	include Mongoid::Document
	include Mongoid::Timestamps
	has_many :comments, dependent: :destroy
	
	field :title, type: String
	field :text, type: String

	validates :title, presence: true
	validates :text, presence: true, length: { minimum: 15 }
end

blog/app/models/comment.rb
class Comment
	include Mongoid::Document
	include Mongoid::Timestamps
	belongs_to :article
	
	field :commenter, type: String
	field :body, type: String
	
	validates :commenter, presence: true
	validates :body, presence: true
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
	end
	
	def create
		@article = Article.new(params.require(:article).permit(:title, :text))
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end
	
	def show
		@article = Article.find(params[:id])
	end
	
	def index
		@articles = Article.all
	end
	
	def edit
		@article = Article.find(params[:id])
	end
	
	def update
		@article = Article.find(params[:id])
		if @article.update(params.require(:article).permit(:title, :text))
			redirect_to @article
		else
			render 'edit'
		end
	end
	
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(params.require(:comment).permit(:commenter, :body))
		redirect_to article_path(@article)
	end
	
	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end
	
	def edit
		@comment = Comment.find(params[:id])
	end
	
	def update
		@article = Article.find(params[:article_id])
		@comment = Comment.find(params[:id])
		if @comment.update(params.require(:comment).permit(:commenter, :body))
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/edit.html.erb
<div class="navbar navbar-inverse container-fluid">
	<%= link_to "Blog", articles_path, {:class => "nome_blog"} %>
</div>

<h1>Editar Artigo</h1>

<div class="div-form-comentario container-fluid">
	<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
		<% if !@article.nil? && @article.errors.any? %>
			<div id="error_explanation">
				<p>
					<%= pluralize(@article.errors.count, "error") %> prohibited
					this article from being saved:
				</p>
				<ol>
					<% @article.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ol>
			</div>
		<% end %>

		<div class="form-group">
			<%= f.label "Título" %>
			<%= f.text_field :title, :class => "form-control" %><br>
		</div>
	
		<div class="form-group">
			<%= f.label "Conteúdo" %>
			<%= f.text_area :text, :class => "form-control" %>
		</div>
	 
		<div class="form-group">
			<%= f.submit "Enviar", :class => "btn btn btn-default" %>
			<%= link_to articles_path do %>
				<div class="btn btn-default">Cancelar</div>
			<% end %>
		</div>
	<% end %>
</div>

blog/app/views/articles/index.html.erb
<%
	require 'time'
	def formatar_data( data )
		return Time.parse(data.to_s).strftime("%d/%m/%Y - %H:%M")
	end
	
	total = 10
	if params[:pag].blank? || params[:pag].to_i < 1
		pagina = 1
	else
		pagina = params[:pag].to_i
	end
%>

<div class="navbar navbar-inverse container-fluid">
	<%= link_to "Blog", articles_path, {:class => "nome_blog"} %>
	<%= link_to new_article_path do %>
		<div class="btn btn-default navbar-btn">Novo Artigo</div>
	<% end %>
</div>

<h1>Artigos</h1>
<% @articles.reverse[(pagina-1)*total,total].each do |article| %>
	<div class="container-fluid col-sm-4">
		<div class="panel panel-default">
			
			<div class="panel-heading">
				<%= article.title %><br/>
			</div>
			
			<div class="panel-body">
				<%= article.text[0, 50] %><br/><br/>
				<small>Criado em <%= formatar_data(article.created_at) %></small>
			</div>
			
			<div class="panel-footer clearfix">
				<div class="pull-right">
					<%= link_to 'Apagar', article_path(article),
						{:class => "btn btn btn-default",
						method: :delete,
						data: {confirm: 'Deseja excluir?'}}%>					

					<!--<%= link_to 'Editar', edit_article_path(article),
						{:class => "btn btn-default"} %>-->
				
					<%= link_to 'Ver', article_path(article),
						{:class => "btn btn-primary"} %>
				</div>
			</div>
			
		</div>
	</div>
<% end %>

<nav class="navbar navbar-default navbar-fixed-bottom seletor-pagina">
	<% [*1..(@articles.size-1)/total+1].each do |numero| %>
		<%= link_to numero, articles_path(pag:numero ) %>
		&nbsp;
	<% end %>
</nav>

blog/app/views/articles/new.html.erb
<div class="navbar navbar-inverse container-fluid">
	<%= link_to "Blog", articles_path, {:class => "nome_blog"} %>
</div>

<h1>Novo Artigo</h1>

<div class="div-form-comentario container-fluid">
	<%= form_for :article, url: articles_path do |f| %>
		<% if !@article.nil? && @article.errors.any? %>
			<div id="error_explanation">
				<p>
					<%= pluralize(@article.errors.count, "error") %> prohibited
					this article from being saved:
				</p>
				<ol>
					<% @article.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ol>
			</div>
		<% end %>

		<div class="form-group">
			<%= f.label "Título" %>
			<%= f.text_field :title, :class => "form-control" %><br>
		</div>
	
		<div class="form-group">
			<%= f.label "Conteúdo" %>
			<%= f.text_area :text, :class => "form-control" %>
		</div>
	 
		<div class="form-group">
			<%= f.submit "Enviar", :class => "btn btn btn-default" %>
			<%= link_to articles_path do %>
				<div class="btn btn-default">Cancelar</div>
			<% end %>
		</div>
	<% end %>
</div>

blog/app/views/articles/show.html.erb
<%
	require 'time'
	def formatar_data( data )
		return Time.parse(data.to_s).strftime("%d/%m/%Y - %H:%M")
	end
	
	total = 10
	if params[:pag].blank? || params[:pag].to_i < 1
		pagina = 1
	else
		pagina = params[:pag].to_i
	end
%>

<div class="navbar navbar-inverse container-fluid">
	<%= link_to "Blog", articles_path, {:class => "nome_blog"} %>
	<%= link_to edit_article_path(@article) do %>
		<div class="btn btn-default navbar-btn">Editar</div>
	<% end %>
</div>

<h1><%= @article.title %></h1>

<article class="container-fluid">
	<%= @article.text %><br/><br/>
	<small>Postado em: <%=formatar_data(@article.created_at)%><br/>
	Última atualização: <%=formatar_data(@article.updated_at)%></small>
</article>
<hr/>


<div class="container-fluid">
	<h2 id="comentarios">Comentários</h2>
	
	<% @article.comments.reverse[(pagina-1)*total,total].each do |comment| %>
		<strong>
			<%= comment.commenter %>
		</strong>&nbsp;&nbsp;&nbsp;&nbsp;
		<%= link_to 'Editar', edit_article_comment_path(comment.article, comment) %> -
		<%= link_to 'Deletar', [comment.article, comment], method: :delete, data: { confirm: 'Deseja excluir?' } %>
		
		<div class="container-fluid">
			<small>Postado em: <%=formatar_data(comment.created_at)%> /
			Última atualização: <%=formatar_data(comment.updated_at)%></small><br/>
			<%= comment.body %>
		</div>
		<hr/>
	<% end %>
	
	<nav class="seletor-pagina">
		<% [*1..(@article.comments.size-1)/total+1].each do |numero| %>
			<%= link_to numero, article_path(@article, anchor: "comentarios", pag:numero ) %>
		<% end %>
	</nav>
	
	<%= form_for([@article, @article.comments.build]) do |f| %>
		<div class="form-group">
			<%= f.label :Nome %><br>
			<%= f.text_field :commenter, :class => "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :Comentário %><br>
			<%= f.text_area :body, :class => "form-control" %>
		</div>
		<div class="form-group">
			<%= f.submit %>
		</div>
	<% end %>
</div>

blog/app/views/comments/edit.html.erb
<div class="navbar navbar-inverse container-fluid">
	<%= link_to "Blog", articles_path, {:class => "nome_blog"} %>
</div>

<h1>Editar Comentário</h1>

<div class="div-form-comentario container-fluid">
	<%= form_for :comment, url: article_comment_path(@comment.article, @comment), method: :patch do |f| %>
		<% if !@comment.nil? && @comment.errors.any? %>
			<div id="error_explanation">
				<p>
					<%= pluralize(@comment.errors.count, "error") %> prohibited
					this article from being saved:
				</p>
				<ol>
					<% @comment.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ol>
			</div>
		<% end %>

		<div class="form-group">
			<%= f.label "Nome" %>
			<%= f.text_field :commenter, :class => "form-control" %><br>
		</div>
	
		<div class="form-group">
			<%= f.label "Comentário" %>
			<%= f.text_area :body, :class => "form-control" %>
		</div>
	 
		<div class="form-group">
			<%= f.submit "Enviar", :class => "btn btn btn-default" %>
			<%= link_to articles_path do %>
				<div class="btn btn-default">Cancelar</div>
			<% end %>
		</div>
	<% end %>
</div>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/welcome/index.html.erb
<h1>Ok</h1>
<%= link_to 'My Blog', controller: 'articles' %><br/>